name: Deploy to Cloudflare Workers

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-24.04
    name: Deploy
    defaults:
      run:
        working-directory: ./cloudflare-worker/cf-worker-demo
    steps:
      - uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.23"
          cache-dependency-path: ./cloudflare-worker/cf-worker-demo/go.sum

      - name: Setup TinyGo
        run: |
          wget https://github.com/tinygo-org/tinygo/releases/download/v0.35.0/tinygo_0.35.0_amd64.deb
          sudo dpkg -i tinygo_0.35.0_amd64.deb

      - name: Build
        run: make build

      - name: Deploy
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          workingDirectory: "cloudflare-worker/cf-worker-demo"
